# deployment do postgres

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kube-news
            - name: POSTGRES_USER
              value: kube-news
            - name: POSTGRES_PASSWORD
              value: kube-news1234

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kube-news
        image: orlandirafael/kube-news:v1
        env:
          - name: DB_USERNAME
            value: kube-news
          - name: DB_PASSWORD
            value: kube-news1234
          - name: DB_DATABASE
            value: kube-news
          - name: DB_HOST
            value: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer