name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usuário no docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviando para o docker-hub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            orlandirafael/kube-news:${{github.run_number}}
            orlandirafael/kube-news:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
  
      - name: Define o contexto do kubernets
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: $${{secrets.K8S_CONFIG}}

      - name: Efetua o deploy no cluster kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          images: orlandirafael/kube-news:${{github.run_number}}
          manifests: |
            ./src/k8s/deployment.yaml
